
public enum Move2D {
	UNYAW,    // LEFT_TO_RIGHT
	YAW,      // RIGHT_TO_LEFT
	UNPITCH,  // UP_TO_DOWN
	PITCH,    // DOWN_TO_UP
	ROLL,     // CIRCULAR_HOUR
	UNROLL,   // CIRCULAR_ANTI_HOUR
	DEFINED; 
}
